[build-system]
requires = ["setuptools>=61", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "simple_dag"
dynamic = ["version"]
description = "Create simple Pipelines with Python"
readme = "README.md"
license = {file = "LICENSE"}
authors = [{name = "Tim Rohner", email = "info@timrohner.ch"}]
keywords = ["simple_dag"]
# homepage = "https://github.com/leokster/simple_dag"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12"
]
dependencies = [
    "aiohttp >=3.9.0, <4",
    "Click>=8.0, <=9",
    "dagster-webserver >= 1.5.0, <= 2",
    "dagster >= 1.5.0, <= 2",
    "fsspec >=2023.1.0",
    "matplotlib >=3.7.0, <=4",
    "pandas >=2.1.0, <=3",
    "requests >=2.28.0, <3",
]

[project.urls]
Source = "https://github.com/leokster/simple_dag"


[project.optional-dependencies]
dev = [
    "black >= 24.0.0, <= 25",
    "tox >= 3.14.0, <= 4.54.0",
    "twine >= 6"
]


[tool.setuptools.packages.find]
include = ["simple_dag", "simple_dag.*"]

[tool.setuptools.package-data]
simple_dag = ["py.typed"]

[tool.setuptools_scm]
write_to = "simple_dag/_version.py"
